/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY ,
    name varchar(50) NOT NULL,
    date_of_birth date,
    escape_attempts INTEGER,
    neutered boolean,
    weight_kg decimal(4,2),
    species varchar(50)
);
