/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY ,
    name varchar(50) NOT NULL,
    date_of_birth date,
    escape_attempts INTEGER,
    neutered boolean,
    weight_kg decimal(8,2),
    species varchar(50)
);

-- Make id autoincremented primary key
ALTER TABLE animals ADD PRIMARY KEY (id);

-- Remove the "species" column
ALTER TABLE animals DROP COLUMN species;

-- Add the "species_id" and "owner_id" columns as foreign keys
ALTER TABLE animals ADD COLUMN species_id INTEGER REFERENCES species(id), ADD COLUMN owner_id INTEGER REFERENCES owners(id);

CREATE TABLE owners (
    id SERIAL PRIMARY KEY,
    full_name VARCHAR(255),
    age INTEGER
);

CREATE TABLE species (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255)
);

-- Create the "vets" table
CREATE TABLE vets (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    age INTEGER,
    date_of_graduation DATE
);

-- Create the "specializations" join table
CREATE TABLE specializations (
    vet_id INTEGER REFERENCES vets(id),
    species_id INTEGER REFERENCES species(id),
    PRIMARY KEY (vet_id, species_id)
);

-- Create the "visits" join table
CREATE TABLE visits (
    vet_id INTEGER REFERENCES vets(id),
    animal_id INTEGER REFERENCES animals(id),
    visit_date DATE,
    PRIMARY KEY (vet_id, animal_id, visit_date)
);

--Performance activity

ALTER TABLE owners ADD COLUMN email VARCHAR(120);

This will add 3.594.280 visits considering you have 10 animals, 4 vets, and it will use around ~87.000 timestamps (~4min approx.)
INSERT INTO visits (animal_id, vet_id, date_of_visit) SELECT * FROM (SELECT id FROM animals) animal_ids, (SELECT id FROM vets) vets_ids, generate_series('1980-01-01'::timestamp, '2021-01-01', '4 hours') visit_timestamp;

This will add 2.500.000 owners with full_name = 'Owner <X>' and email = 'owner_<X>@email.com' (~2min approx.)
insert into owners (full_name, email) select 'Owner ' || generate_series(1,2500000), 'owner_' || generate_series(1,2500000) || '@mail.com';

CREATE INDEX idx_animal_id ON visits (animal_id);
ANALYZE visits;
EXPLAIN ANALYZE SELECT COUNT(*) FROM visits where animal_id = 4;

CREATE INDEX idx_vet_id ON visits (vet_id);
ANALYZE visits;
EXPLAIN ANALYZE SELECT * FROM visits where vet_id = 2;

CREATE INDEX idx_email ON owners (email);
EXPLAIN ANALYZE SELECT * FROM owners where email = 'owner_18327@mail.com';
